### PR TITLE
functionality to refresh session birthdate

### PR DESCRIPTION
**Pull request by jread-usgs**
work in progress for #77 

Waiting on PR #76 because this call should go right before the `return()` on the REST helper calls.

### CODE REVIEW

**Comment by jread-usgs** [comment]
@lawinslow should this PR be killed? It has been open for a long time.

**Comment by lawinslow** [comment]
Hmmm, good question. I'm grappling with how we want to handle this. Do we want to store this internal state, or would we rather just improve our handling of errors when they occur? (e.g., Check auth via #90 when we hit unexpected behavior, suggest the user re-auth, something like that)

Also, currently, this PR doesn't use the session age within any of the functions, right?

**Comment by lawinslow** [comment]
@sckott any thoughts?

**Comment by jread-usgs** [comment]
yeah, I think this is a hold over from some of the earlier discussions regarding handling the timeouts. I do think age actually is used in the package. @aappling-usgs has run into is, as have I (after an hour) I think?

**Comment by jread-usgs** [comment]
see https://github.com/USGS-R/sbtools/blob/master/R/session_validate.R#L36

**Comment by lawinslow** [comment]
Hmmm, yeah ok. We are half implemented here, aren't we. Let's merge this and see where we go with error handling in the future.

**Comment by sckott** [comment]
yeah, was going to say merge sounds good

**Comment by jread-usgs** [comment]
hi @sckott :smile_cat:

**Comment by sckott** [comment]
hi!

**Comment by lawinslow** [comment]
PR meetup!

**Pull request merged**
