### PR TITLE
roxy and #16

### PR DESCRIPTION
**Pull request by jread-usgs**
#16

### CODE REVIEW

**Comment by jread-usgs** [comment]
@lawinslow look ok?

**Comment by jread-usgs** [comment]
```R
item_list_children('5060b03ae4b00fc20c4f3c8b')
                         id
1  50c11b70e4b005831885e44f
2  50c11b75e4b005831885e6d5
3  50c11b77e4b005831885e7dd
4  50c11b7ae4b005831885e98b
5  50c11c04e4b005831885f02a
6  50c11c05e4b005831885f0ae
7  50c11c05e4b005831885f0b0
8  50c11c06e4b005831885f126
9  50c11c09e4b005831885f34e
10 50c11c12e4b005831885f932
11 50c11c20e4b0058318860242
12 50c11c22e4b00583188603bc
13 50c1285fe4b002407f2233ba
14 50c11b7ae4b005831885e959
15 50c11b7ae4b005831885e973
16 50c11bfce4b005831885eb5c
17 50c11bfce4b005831885eb68
18 50c11bfde4b005831885eb76
19 50c11c03e4b005831885ef36
20 50c11c04e4b005831885f036
```

**Comment by jread-usgs** [comment]
added that NULL filter and removed the error for missing(type) when key and scheme are there. #15

**Comment by lawinslow** [comment]
Looks good

**Pull request merged**
