### PR TITLE
switch to donttest so CRAN checks don't fail when SB is down.

### LINKED ISSUE #250: sbtools is archived on CRAN
https://cran.r-project.org/web/packages/sbtools/index.html

> Package ‘sbtools’ was removed from the CRAN repository.
Formerly available versions can be obtained from the archive.
Archived on 2019-05-13 for policy violation.

### PR DESCRIPTION
**Pull request by dblodgett-usgs**
[sbtools_1.1.8.tar.gz](https://github.com/USGS-R/sbtools/files/3952291/sbtools_1.1.8.tar.gz)

Fixes #250 tar.gz is attached to be uploaded to cran. 🤞 that does the trick.

### CODE REVIEW

**Comment by jread-usgs** [comment]
ignoring travis on this since that error is unrelated

**Comment by dblodgett-usgs** [comment]
The travis.yml over in nhdplusTools should have an example that will get rgdal working... should I port that over here?

**Comment by jread-usgs** [comment]
if you are up for it, that would be great. Ideally, we'd have working CI on this repo 👍

**Comment by dblodgett-usgs** [comment]
OK -- I se a couple other easy issues in here I could pick off -- it's on my list.

**Pull request merged**
