### PR TITLE
1-line change to permit download of tsv files

### PR DESCRIPTION
**Pull request by aappling-usgs**
@lawinslow - this OK with you?

### CODE REVIEW

**Comment by lawinslow** [comment]
Sure. That type checking is a bit of a hack anyway to try and differentiate from success and error conditions.

**Comment by lawinslow** [comment]
Patch Version increment?

**Comment by aappling-usgs** [comment]
Yeah, I know we've discussed other options in the past. Hopefully this commit will add a little bit more info to the ongoing discussion - turns out tsvs are another sometimes-permissible result type.

**Comment by aappling-usgs** [comment]
sure, done.

**Pull request merged**
