### PR TITLE
new: item_get_fields, query_item_in_folder

### PR DESCRIPTION
**Pull request by aappling-usgs**

### CODE REVIEW

**Comment by aappling-usgs** [comment]
@lawinslow - added these for my use, probably useful to others. what do you think?

**Comment by aappling-usgs** [comment]
ok, about to push an update. having this problem with R CMD check:
```
Running the tests in 'tests/testthat.R' failed.
Last 13 lines of output:
  sbtools_GET : .....
  authentication : .....
  
  
  1. Failure(@test-REST.R#15): generic post fails w/o auth -----------------------
  item_append_files("54e265a4e4b08de9379b4dfb", files, session = session) does not match 'POST failed to'. Actual value: "Error in curl::curl_fetch_memory(url, handle = handle) : \n  Timeout was reached\n"
  
  Error: Test failures
  In addition: Warning messages:
  1: Cookies argument is depcrated 
  2: Cookies argument is depcrated 
  3: Cookies argument is depcrated 
  Execution halted
* DONE
Status: 1 ERROR, 1 NOTE
```
which i'm hoping is due to my location (car repair shop), especially because i didn't touch `item_append_files`. 

also note that `Cookies argument is depcrated`, though - that looks like something to address at some point.

**Comment by lawinslow** [comment]
Weird. Let's see what travis says. It's probably fine. Cookies must have deprecated with v1.0.0. Adding issue for later.

**Comment by aappling-usgs** [comment]
@lawinslow passing!

**Comment by jread-usgs** [comment]
any issues w/ merging this?

**Comment by aappling-usgs** [comment]
merging is good with me. @lawinslow ?

**Comment by lawinslow** [comment]
@aappling-usgs any clue what item this was? 
https://github.com/USGS-R/sbtools/search?utf8=%E2%9C%93&q=557ec671e4b023124e8ef590
and why it's not available for that test anymore?

**Comment by jread-usgs** [comment]
I had that in there as a public item that could be snagged with GET.

**Comment by lawinslow** [comment]
Ok, is it not a public item now? Or should we setup a new public item for that test? It seems to be [failing](https://travis-ci.org/USGS-R/sbtools).

**Comment by aappling-usgs** [comment]
Is there a good place on SB to store a public item for an sbtools test?

**Comment by aappling-usgs** [comment]
Also, if you have any plans to put this on CRAN, might want to think about making tests that use SB be non-automatic, based on @ldecicco-USGS's dataRetrieval experience...

**Comment by lawinslow** [comment]
Not sure about public item. I wonder if their featured item is stable
https://www.sciencebase.gov/catalog/item/4f4e4a62e4b07f02db636b68

**Comment by jread-usgs** [comment]
I think it got lost/yanked in some recent clean up.

**Pull request merged**
