### PR TITLE
Package interface changes

### PR DESCRIPTION
**Pull request by sckott**
for #105 

Implemented changes I think all places where it makes sense to do. 

These changes make it so that in every function that accepts an Sciencebase item/folder ID, it also accepts an object of class `sbitem`. Many of the functions also output an `sbitem` class object. This is kinda nice cause it makes is so that you can chain together outputs of function X into function Y and so on - if you desire of course.  

Some of the functions that take in SB item ID or object of class `sbitem` __do not__ output an `sbitem` class object - we could think of whether it makes sense to make some of these output an `sbitem` class object  - some are close to fitting, whereas others probably don't make sense at all. 

I did a bit of code tidying while I was in there...

### CODE REVIEW

**Comment by sckott** [comment]
Build failing, I'll see if it's due to my changes and fix if it is

**Comment by sckott** [comment]
Did you have any comments on my PR?

**Comment by sckott** [comment]
travis build passing now

**Comment by aappling-usgs** [comment]
Looks good to me. I really like the chaining. And the code tidying. @lawinslow is switching continents now, so he might be away from internet for a while.

**Comment by sckott** [comment]
Thx, chaining is nice - of course not everyone likes that, but they don't have to do that. 

safe travels @lawinslow

**Comment by lawinslow** [comment]
@sckott, looks good. Two things. 

1. Could you change `item_create` so it accepts an sbitem as parent? Seems like a nice use. Create an item, add sub-items to it, etc. 

2. Thoughts on using `user_id` as default parent for `item_create`? I'm in favor.

**Comment by lawinslow** [comment]
Oh yeah, version bump too?

**Comment by sckott** [comment]
> Could you change item_create so it accepts an sbitem as parent?

Yes

> Thoughts on using `user_id` as default parent for `item_create`

Do you mean default value for its first parameter `parent_id` ?  If so, yeah, sounds good. 

Yeah, version. to what?

**Comment by lawinslow** [comment]
Yeah, default for parent_id. And version, dunno, how about 0.12.0?

**Comment by sckott** [comment]
okay, changed

**Pull request merged**
