### PR TITLE
page through query results (fix #131)

### LINKED ISSUE #131: return >1000 items in query_item_identifier
`query_item_identifier` can handle pretty big, but not very big, sets of items. Where `bigscheme` and `bigtype` indicate a collection of SB items larger than 1000 items, only 1000 are returned even if limit=10000. Make limit 100000 and you even get an error about that parameter (which gets renamed 'max' before being passed to SB).
```r
> itemlist <- query_item_identifier(scheme = bigscheme, type = bigtype, limit = 100000)
 Error: Invalid 'max' parameter (not a valid number) 
4 stop(content(x)$errors$message, call. = FALSE) at REST_helpers.R#105
3 handle_errors(r, url, "GET", supported_types) at REST_helpers.R#41
2 sbtools_GET(url = pkg.env$url_items, ..., query = query, session = session) at query_item_identifier.R#25
1 query_item_identifier(scheme = bigscheme, type = bigtype, limit = 1e+05)
```

I think the solution is to page through the results and combine them within R. See https://my.usgs.gov/confluence/display/sciencebase/Creating+Queries+for+ScienceBase#CreatingQueriesforScienceBase-Gettingmorethan20results

### PR DESCRIPTION
**Pull request by aappling-usgs**
Check the Travis results carefully. I only changed 3 files, none of them relevant to test-REST, but I'm getting a test failure (stops + warnings) on R CMD check. The cookies warning ('Cookies argument is depcrated') comes from httr::handle(..., cookies=FALSE) - I just updated my httr package. The Failures occur when I run the tests manually, too, unless I login to SB first. I think it makes sense for those three tests (lines 5, 10, and 14 of test-REST) to fail as they do below. How are these things passing without warning or error on Travis??

```r
* checking tests ...
  Running 'testthat.R' ERROR
Running the tests in 'tests/testthat.R' failed.
Last 13 lines of output:
  OK: 14 SKIPPED: 0 FAILED: 3
  1. Failure (at test-REST.R#5): generic post fails w/o auth 
  2. Failure (at test-REST.R#10): generic post fails w/o auth 
  3. Failure (at test-REST.R#14): generic post fails w/o auth 
  
  Error: testthat unit tests failed
  In addition: Warning messages:
  1: Cookies argument is depcrated 
  2: Cookies argument is depcrated 
  3: Cookies argument is depcrated 
  4: Cookies argument is depcrated 
  5: Cookies argument is depcrated 
  Execution halted
* checking PDF version of manual ... [11s]
Warning message:
running command '"C:/PROGRA~1/R/R-32~1.2/bin/x64/R" CMD BATCH --vanilla  "testthat.R" "testthat.Rout"' had status 1 
 OK
* DONE
111

### CODE REVIEW

**Comment by aappling-usgs** [comment]
Well, hmm. Travis passes - that's good, but I don't understand why it's failing for me locally. Do you have any ideas, @sckott ?

**Comment by sckott** [comment]
Hmm, I'm not sure. I don't think any tests rely on authenticated session, do they?

Running tests with this branch locally, and they run fine for me.

**Comment by jread-usgs** [comment]
no, we don't use actual auth in the tests. We kind of mock it up on the timeout test I think, but no actual pwds

**Comment by aappling-usgs** [comment]
Update: the tests pass for me when I use Ctrl-Shift-T in RStudio, but [still] not when I do Check. Currently testing a hypothesis (via Travis and my most recent commit) that having added one `Sys.sleep(2)` call to the start of test-REST.R, this will now break for everyone.

I think it's because test-expiration.R comes right before test-REST.R, and maybe Check was slower on my computer. I suggest this because if I manually run
`test_that("session age works on internal session", {...})` right before `test_that("generic post fails w/o auth", {...})`, they both pass, but if I run test_that("generic post fails w/o auth", {...})` separately a few seconds later, it fails again with authentication errors:
```r
Error: Test failed: 'generic post fails w/o auth'
* Not expected: item_append_files("54e265a4e4b08de9379b4dfb", "/foo/bar/baz.zip") does not match 'Item not found for'. Actual value: "Error : session is not authorized. See ?authenticate_sb\n".
* Not expected: item_append_files("54e265a4e4b08de9379b4dfb", "/foo/bar/baz.zip", session = session) does not match 'Item not found for'. Actual value: "Error : session is not authorized. See ?authenticate_sb\n".
* Not expected: item_append_files("54e265a4e4b08de9379b4dfb", files, session = session) does not match 'Item not found for'. Actual value: "Error : session is not authorized. See ?authenticate_sb\n".
In addition: Warning message:
Cookies argument is depcrated 
```

`item_append_files` does, indeed, require an authenticated session. I think that makes sense, because the user is modifying files on SB. But it actually gets caught in the first line of the function, `as.sbitem(id)`, even before the `sbtools_POST` call on the following line. Might be nice if `as.sbitem(id)` could be run without requiring authentication for public items - I'll look for/add to a separate issue on that. (And then `sbtools_POST` also has a call to `check_session(session)`, so we'd also fail on that line of `item_append_files` if we ever made it that far.) Traceback from just that call:
```r
item_append_files("54e265a4e4b08de9379b4dfb", '/foo/bar/baz.zip')
 Error: session is not authorized. See ?authenticate_sb 
7 stop("session is not authorized. See ?authenticate_sb", call. = FALSE) at REST_helpers.R#110
6 check_session(session) at REST_helpers.R#39
5 sbtools_GET(url = paste0(pkg.env$url_item, id), ..., query = list(type = "json"), 
    session = session) at item_get.R#22
4 item_get(x, ...) at sb_item.R#32
3 as.sbitem.character(id) at sb_item.R#29
2 as.sbitem(id) at item_append_files.R#23
1 item_append_files("54e265a4e4b08de9379b4dfb", "/foo/bar/baz.zip") 
```

**Comment by aappling-usgs** [comment]
OK, hypothesis supported. @sckott , I think the immediate solution is to keep the Sys.sleep(2) (or is there a faster way to log out?) and then change the expectations of the `expect_error`s in test-REST.R to expect "session is not authorized". I can do this, but @sckott , since you've been the primary developer recently, I want to check with you first - does that sound like the right way to go, or would you rather change the code in `item_append_files` so that 'Item not found for' gets called before we ever check for authentication?

**Comment by sckott** [comment]
I'm not super familiar with the best way to log out.  I'll get up to speed on how ScienceBase auth works soon. (I don't often work with cookies either, so that's new to me)

**Comment by aappling-usgs** [comment]
ok, i've deleted that one session check in sbtools_GET (per #134 & needed to fix tests for this PR). i've also updated those REST tests to not use the `cookies` argument (it was throwing those warnings and gets totally ignored, anyway) and to only test for public and non-existent items. Would be interested in eventually testing for access to private items, but we'd need an SB account specifically for public (GitHub/Travis) tests, which sounds like a tricky nut to crack.

**Comment by sckott** [comment]
@aappling-usgs see  #136

**Pull request merged**
