### PR TITLE
Fleshing out manuscript text and examples

### PR DESCRIPTION
**Pull request by lawinslow**
There are a lot of commits, ignore most of them. Just figuring out formatting with online CI.

### CODE REVIEW

**Comment by sckott** [comment]
wow, all the commits are belong to luke

**Comment by lawinslow** [comment]
I am not good with LaTeX

**Comment by jread-usgs** [comment]
do you want the ms stuff to be a branch of this project?

**Comment by lawinslow** [comment]
I'm ambivalent. Think there's a strong reason one way or another?

**Comment by sckott** [comment]
I don't have a preference - carl likes to do his in the pkg itself on master - though i prefer a completely separate repo, but

**Comment by jread-usgs** [comment]
to not clutter the repo w/ something out of scope of the package.

**Comment by sckott** [comment]
yeah, but i guess its just potato/potato

**Comment by lawinslow** [comment]
Ha, that phrase works better when spoken. 

Unless someone wants to veto, I'll just leave it in the package on master. It's simple and I don't think it hurts.

**Comment by jread-usgs** [comment]
fine by me.

**Comment by sckott** [comment]
sounds good

**Pull request merged**
